version: '3'
services:
  redis-stack:
    container_name: fastapi-redis-stack
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - fastapi_redis_network
    volumes:
      - redis_data:/data
    environment:
      REDIS_ARGS: --save 20 1 # Necessary for data pesistance for the redis/redis-stack image

  fastapi_app:
    container_name: fastapi_app
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - redis-stack
    networks:
      - fastapi_redis_network
    env_file:
      - .env

  celery_app:
    container_name: celery_app
    build:
      context: ./celery
    depends_on:
      - redis-stack
      - fastapi_app
    networks:
      - fastapi_redis_network
    env_file:
      - .env

networks:
  fastapi_redis_network:
    driver: bridge

volumes:
  redis_data:
